services:
  - name: aws-west
    description: aws-west
    target: aws-west
    ports:
      port: 80
      localPort: 8000
    profile: aws-west
    region: us-west-2
  - name: us-east
    description: us-east 
    target: us-east 
    ports:
      port: 80
      localPort: 8000
    profile: us-east 
    region: us-east-2 
